# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_app', '0002_auto_20160719_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='byn',
            field=models.CharField(default=45, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='byr',
            field=models.CharField(default='0', max_length=8, null=True),
        ),
    ]
