# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_app', '0004_auto_20160719_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='test',
            field=models.CharField(default=800, max_length=100),
        ),
    ]
