# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_app', '0007_auto_20160719_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='byn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='byr',
            field=models.IntegerField(default=0),
        ),
    ]
