# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_app', '0009_auto_20160719_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='test',
        ),
    ]
