# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_app', '0010_remove_orders_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date_create',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
